name: Build and test various examples

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildDir: ["cli/1","cli/2", "cli/3", "cli/4","cli/5",
                   "config/1", "config/2", "config/3", "config/4"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build example
      run: (cd ${{ matrix.buildDir }}; go build -v ./...)
